// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"portsMaster/pkg/config"
	"portsMaster/pkg/model"
)

func Search(data *model.SiteData, cfg *config.Config, currentPath string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"breadcrumb\"><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 templ.SafeURL
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinURLErrs(Href(currentPath, "/"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/search.templ`, Line: 11, Col: 35}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">home</a> / search</div><div class=\"section-header\">Advanced Search</div><form class=\"search-form\" id=\"searchForm\"><div class=\"search-row\"><label for=\"query\">Search Query</label> <input type=\"text\" id=\"query\" name=\"query\" placeholder=\"enter search terms or filter expression...\"><div class=\"search-examples\"><code>curl</code> - simple text search<br><code>name:git AND category:devel</code> - logical operators<br><code>provides:/usr/bin/vim</code> - file path search<br><code>depends:libressl OR depends:openssl</code> - dependency search<br><code>NOT category:devel</code> - negation<br><code>is:broken</code> - find build failures<br><code>is:new</code> - updated in last 30 days<br><code>since:7d</code> - updated in last 7 days<br><code>description:\"web server\"</code> - exact phrase match</div></div><div class=\"filter-group\"><div class=\"filter-group-header\">Search In</div><div class=\"filter-option\"><input type=\"checkbox\" id=\"search_name\" checked> <label for=\"search_name\">Port Name</label></div><div class=\"filter-option\"><input type=\"checkbox\" id=\"search_desc\" checked> <label for=\"search_desc\">Description</label></div><div class=\"filter-option\"><input type=\"checkbox\" id=\"search_files\"> <label for=\"search_files\">File Paths (provides)</label></div><div class=\"filter-option\"><input type=\"checkbox\" id=\"search_deps\"> <label for=\"search_deps\">Dependencies</label></div></div><div class=\"filter-group\"><div class=\"filter-group-header\">Filters</div><div class=\"search-row\"><label>Category</label> <select name=\"category\" id=\"filter-category\"><option value=\"\">any</option> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, c := range data.Categories {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<option value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(c.Name)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/search.templ`, Line: 59, Col: 29}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(c.Name)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/search.templ`, Line: 59, Col: 40}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</option>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</select></div></div><div class=\"button-row\"><input type=\"submit\" value=\"search\"> <input type=\"reset\" value=\"clear\"></div></form><div id=\"results\" class=\"results display-none\"><div class=\"result-stats\">Found <strong id=\"resultCount\">0</strong> ports matching query: <code id=\"queryDisplay\"></code> (search took <span id=\"searchTime\">0</span>ms)</div><table id=\"resultsTable\"><thead><tr><th>Port</th><th>Version</th><th>Category</th><th>Description</th></tr></thead> <tbody id=\"resultsBody\"></tbody></table></div><div class=\"section-header\">Filter Syntax Reference</div><table><thead><tr><th>Filter</th><th>Description</th><th>Example</th></tr></thead> <tbody><tr><td><code>name:TERM</code></td><td>Search in port name</td><td><code>name:curl</code></td></tr><tr><td><code>description:TERM</code></td><td>Search in description</td><td><code>description:editor</code></td></tr><tr><td><code>category:CAT</code></td><td>Filter by category</td><td><code>category:network</code></td></tr><tr><td><code>provides:PATH</code></td><td>Find package providing file</td><td><code>provides:/usr/bin/git</code></td></tr><tr><td><code>depends:PKG</code></td><td>Find packages depending on PKG</td><td><code>depends:musl</code></td></tr><tr><td><code>AND</code></td><td>Logical AND operator</td><td><code>name:lib AND category:system</code></td></tr><tr><td><code>OR</code></td><td>Logical OR operator</td><td><code>category:audio OR category:video</code></td></tr><tr><td><code>NOT</code></td><td>Logical NOT operator</td><td><code>NOT license:GPL</code></td></tr><tr><td><code>\"phrase\"</code></td><td>Exact phrase match</td><td><code>description:\"text editor\"</code></td></tr></tbody></table>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Search", data, cfg, currentPath).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
